name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dart-packages:
    name: Dart packages (format, test)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies (autoverpod_annotation)
        run: flutter pub get
        working-directory: autoverpod_annotation

      - name: Install dependencies (autoverpod_generator)
        run: flutter pub get
        working-directory: autoverpod_generator

      - name: Install dependencies (example)
        run: flutter pub get
        working-directory: example

      - name: Format check
        run: dart format --output=none --set-exit-if-changed autoverpod autoverpod_annotation autoverpod_generator example

      - name: Test autoverpod_generator
        run: dart test
        working-directory: autoverpod_generator

  flutter-package:
    name: Flutter package tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Flutter dependencies
        run: flutter pub get
        working-directory: autoverpod

      - name: Flutter tests
        run: flutter test
        working-directory: autoverpod

