name: Publish autoverpod_annotation to pub.dev

on:
  push:
    tags:
      - 'autoverpod_annotation-v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get
        working-directory: autoverpod_annotation

      - name: Publish to pub.dev
        run: dart pub publish --force
        working-directory: autoverpod_annotation
